<?php

?>
    <script type="text/javascript">
        var customReactConfig = {
            "kitImgDir": '/media/catalog/product/kitproduct/CustomGuitar/',
            "kitHiddenInputName": 'kit-configurable-product',
            "kitHiddenInputClassname": 'kit-simple-product',
            "kitGroups": [
                {
                    "id":1,
                    "name":"Design",
                    "order":1,
                    "subgroups":[
                        {
                            "id":1,
                            "name":"Orientation",
                            "order":1,
                            "options":[
                                {
                                    "id":347742,
                                    "name":"Left",
                                    "order":10,
                                    "price":75,
                                    "description":"Left description text",
                                    "zoomUrl":"customguitar_design_orientation_left_image.png",
                                    "imageUrl":"customguitar_design_orientation_left_smallimage.png",
                                    "iconUrl":"customguitar_design_orientation_left_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347741"
                                },
                                {
                                    "id":347743,
                                    "name":"Right",
                                    "order":20,
                                    "price":50,
                                    "description":"Right description text",
                                    "zoomUrl":"customguitar_design_orientation_right_image.png",
                                    "imageUrl":"customguitar_design_orientation_right_smallimage.png",
                                    "iconUrl":"customguitar_design_orientation_right_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347741"
                                }
                            ]
                        },
                        {
                            "id":2,
                            "name":"Design",
                            "order":2,
                            "options":[
                                {
                                    "id":347756,
                                    "name":"Chrome",
                                    "order":1,
                                    "price":10,
                                    "description":"Chrome description text",
                                    "zoomUrl":"customguitar_design_design_chrome_image.png",
                                    "imageUrl":"customguitar_design_design_chrome_smallimage.png",
                                    "iconUrl":"customguitar_design_design_chrome_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347744"
                                },
                                {
                                    "id":347745,
                                    "name":"Honey",
                                    "order":2,
                                    "price":12,
                                    "description":"Honey description text",
                                    "zoomUrl":"customguitar_design_design_honey_image.png",
                                    "imageUrl":"customguitar_design_design_honey_smallimage.png",
                                    "iconUrl":"customguitar_design_design_honey_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347744"
                                },
                                {
                                    "id":347749,
                                    "name":"Surf Wax",
                                    "order":3,
                                    "price":14,
                                    "description":"Surf Wax description text",
                                    "zoomUrl":"customguitar_design_design_surfwax_image.png",
                                    "imageUrl":"customguitar_design_design_surfwax_smallimage.png",
                                    "iconUrl":"customguitar_design_design_surfwax_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347744"
                                },
                                {
                                    "id":347753,
                                    "name":"Moonshine",
                                    "order":4,
                                    "price":16,
                                    "description":"Moonshine description text",
                                    "zoomUrl":"customguitar_design_design_moonshine_image.png",
                                    "imageUrl":"customguitar_design_design_moonshine_smallimage.png",
                                    "iconUrl":"customguitar_design_design_moonshine_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347744"
                                },
                                {
                                    "id":347746,
                                    "name":"Motor Oil",
                                    "order":5,
                                    "price":17,
                                    "description":"Motor Oil description text",
                                    "zoomUrl":"customguitar_design_design_motoroil_image.png",
                                    "imageUrl":"customguitar_design_design_motoroil_smallimage.png",
                                    "iconUrl":"customguitar_design_design_motoroil_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347744"
                                },
                                {
                                    "id":347750,
                                    "name":"Ale",
                                    "order":6,
                                    "price":18,
                                    "description":"Ale description text",
                                    "zoomUrl":"customguitar_design_design_ale_image.png",
                                    "imageUrl":"customguitar_design_design_ale_smallimage.png",
                                    "iconUrl":"customguitar_design_design_ale_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347744"
                                },
                                {
                                    "id":347754,
                                    "name":"Hot Sauce",
                                    "order":7,
                                    "price":19,
                                    "description":"Hot Sauce description text",
                                    "zoomUrl":"customguitar_design_design_hotsauce_image.png",
                                    "imageUrl":"customguitar_design_design_hotsauce_smallimage.png",
                                    "iconUrl":"customguitar_design_design_hotsauce_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347744"
                                },
                                {
                                    "id":347747,
                                    "name":"Limeade",
                                    "order":8,
                                    "price":20,
                                    "description":"Limeade description text",
                                    "zoomUrl":"customguitar_design_design_limeade_image.png",
                                    "imageUrl":"customguitar_design_design_limeade_smallimage.png",
                                    "iconUrl":"customguitar_design_design_limeade_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347744"
                                },
                                {
                                    "id":347751,
                                    "name":"Blue Body",
                                    "order":9,
                                    "price":22,
                                    "description":"Blue Body description text",
                                    "zoomUrl":"customguitar_design_design_bluebody_image.png",
                                    "imageUrl":"customguitar_design_design_bluebody_smallimage.png",
                                    "iconUrl":"customguitar_design_design_bluebody_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347744"
                                },
                                {
                                    "id":347755,
                                    "name":"Red Body",
                                    "order":10,
                                    "price":23,
                                    "description":"Red Body description text",
                                    "zoomUrl":"customguitar_design_design_redbody_image.png",
                                    "imageUrl":"customguitar_design_design_redbody_smallimage.png",
                                    "iconUrl":"customguitar_design_design_redbody_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347744"
                                },
                                {
                                    "id":347748,
                                    "name":"White Body",
                                    "order":11,
                                    "price":24,
                                    "description":"White Body description text",
                                    "zoomUrl":"customguitar_design_design_whitebody_image.png",
                                    "imageUrl":"customguitar_design_design_whitebody_smallimage.png",
                                    "iconUrl":"customguitar_design_design_whitebody_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347744"
                                },
                                {
                                    "id":347752,
                                    "name":"Black Body",
                                    "order":12,
                                    "price":25,
                                    "description":"Black Body description text",
                                    "zoomUrl":"customguitar_design_design_blackbody_image.png",
                                    "imageUrl":"customguitar_design_design_blackbody_smallimage.png",
                                    "iconUrl":"customguitar_design_design_blackbody_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347744"
                                }
                            ]
                        }
                    ]
                },
                {
                    "id":2,
                    "name":"Neck",
                    "order":2,
                    "subgroups":[
                        {
                            "id":3,
                            "name":"Neck Color",
                            "order":3,
                            "options":[
                                {
                                    "id":347760,
                                    "name":"Cream Neck",
                                    "price":10,
                                    "description":"Cream Neck description text",
                                    "order":0,
                                    "imageUrl":"customguitar_neck_neckcolor_creamneck_smallimage.png",
                                    "iconUrl":"customguitar_neck_neckcolor_creamneck_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347757"
                                },
                                {
                                    "id":347758,
                                    "name":"Blue Neck",
                                    "order":1,
                                    "price":10,
                                    "description":"Blue Neck description text",
                                    "imageUrl":"customguitar_neck_neckcolor_blueneck_smallimage.png",
                                    "iconUrl":"customguitar_neck_neckcolor_blueneck_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347757"
                                },
                                {
                                    "id":347762,
                                    "name":"Red Neck",
                                    "order":2,
                                    "price":10,
                                    "description":"Red Neck description text",
                                    "imageUrl":"customguitar_neck_neckcolor_redneck_smallimage.png",
                                    "iconUrl":"customguitar_neck_neckcolor_redneck_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347757"
                                },
                                {
                                    "id":347759,
                                    "name":"White Neck",
                                    "order":3,
                                    "price":10,
                                    "description":"White Neck description text",
                                    "imageUrl":"customguitar_neck_neckcolor_whiteneck_smallimage.png",
                                    "iconUrl":"customguitar_neck_neckcolor_whiteneck_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347757"
                                },
                                {
                                    "id":347763,
                                    "name":"Black Neck",
                                    "order":4,
                                    "price":10,
                                    "description":"Black Neck description text",
                                    "imageUrl":"customguitar_neck_neckcolor_blackneck_smallimage.png",
                                    "iconUrl":"customguitar_neck_neckcolor_blackneck_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347757"
                                },
                                {
                                    "id":347764,
                                    "name":"Hazel Neck",
                                    "order":6,
                                    "price":10,
                                    "description":"Hazel Neck description text",
                                    "imageUrl":"customguitar_neck_neckcolor_hazelneck_smallimage.png",
                                    "iconUrl":"customguitar_neck_neckcolor_hazelneck_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347757"
                                },
                                {
                                    "id":347761,
                                    "name":"Cherry Neck",
                                    "order":7,
                                    "price":10,
                                    "description":"Cherry Neck description text",
                                    "imageUrl":"customguitar_neck_neckcolor_cherryneck_smallimage.png",
                                    "iconUrl":"customguitar_neck_neckcolor_cherryneck_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347757"
                                }
                            ]
                        },
                        {
                            "id":4,
                            "name":"Headstock",
                            "order":4,
                            "options":[
                                {
                                    "id":347767,
                                    "name":"Natural Headstock",
                                    "order":1,
                                    "price":10,
                                    "description":"Natural Headstock description text",
                                    "imageUrl":"customguitar_neck_headstock_naturalheadstock_smallimage.png",
                                    "iconUrl":"customguitar_neck_headstock_naturalheadstock_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347765"
                                },
                                {
                                    "id":347771,
                                    "name":"Blue Headstock",
                                    "order":2,
                                    "price":12,
                                    "description":"Blue Headstock description text",
                                    "imageUrl":"customguitar_neck_headstock_blueheadstock_smallimage.png",
                                    "iconUrl":"customguitar_neck_headstock_blueheadstock_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347765"
                                },
                                {
                                    "id":347768,
                                    "name":"Red Headstock",
                                    "order":3,
                                    "price":14,
                                    "description":"Red Headstock description text",
                                    "imageUrl":"customguitar_neck_headstock_redheadstock_smallimage.png",
                                    "iconUrl":"customguitar_neck_headstock_redheadstock_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347765"
                                },
                                {
                                    "id":347772,
                                    "name":"White Headstock",
                                    "order":4,
                                    "price":16,
                                    "description":"White Headstock description text",
                                    "imageUrl":"customguitar_neck_headstock_whiteheadstock_smallimage.png",
                                    "iconUrl":"customguitar_neck_headstock_whiteheadstock_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347765"
                                },
                                {
                                    "id":347769,
                                    "name":"Black Headstock",
                                    "order":5,
                                    "price":18,
                                    "description":"Black Headstock description text",
                                    "imageUrl":"customguitar_neck_headstock_blackheadstock_smallimage.png",
                                    "iconUrl":"customguitar_neck_headstock_blackheadstock_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347765"
                                },
                                {
                                    "id":347770,
                                    "name":"Green Headstock",
                                    "order":6,
                                    "price":20,
                                    "description":"Green Headstock description text",
                                    "imageUrl":"customguitar_neck_headstock_greenheadstock_smallimage.png",
                                    "iconUrl":"customguitar_neck_headstock_greenheadstock_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347765"
                                }
                            ]
                        },
                        {
                            "id":5,
                            "name":"Tuners",
                            "order":5,
                            "options":[
                                {
                                    "id":347773,
                                    "name":"Chrome Tuner",
                                    "order":1,
                                    "price":10,
                                    "description":"Chrome Tuner description text",
                                    "imageUrl":"customguitar_neck_tuners_chrometuner_smallimage.png",
                                    "iconUrl":"customguitar_neck_tuners_chrometuner_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347766"
                                },
                                {
                                    "id":347774,
                                    "name":"Black Tuner",
                                    "order":2,
                                    "price":16,
                                    "description":"Black Tuner description text",
                                    "imageUrl":"customguitar_neck_tuners_blacktuner_smallimage.png",
                                    "iconUrl":"customguitar_neck_tuners_blacktuner_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347766"
                                },
                                {
                                    "id":347775,
                                    "name":"Gold Tuner",
                                    "order":3,
                                    "price":20,
                                    "description":"Gold Tuner description text",
                                    "imageUrl":"customguitar_neck_tuners_goldtuner_smallimage.png",
                                    "iconUrl":"customguitar_neck_tuners_goldtuner_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347766"
                                }
                            ]
                        }
                    ]
                },
                {
                    "id":3,
                    "name":"Body",
                    "order":3,
                    "subgroups":[
                        {
                            "id":6,
                            "name":"Pickups",
                            "order":6,
                            "options":[
                                {
                                    "id":347780,
                                    "name":"Humbucker Single Coil White",
                                    "order":1,
                                    "price":10,
                                    "description":"Humbucker Single Coil White description text",
                                    "zoomUrl":"customguitar_body_pickups_humbuckersinglecoilwhite_image.png",
                                    "imageUrl":"customguitar_body_pickups_humbuckersinglecoilwhite_smallimage.png",
                                    "iconUrl":"customguitar_body_pickups_humbuckersinglecoilwhite_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347776"
                                },
                                {
                                    "id":347784,
                                    "name":"Humbucker Single Coil Black",
                                    "order":2,
                                    "price":12,
                                    "description":"Humbucker Single Coil Black description text",
                                    "zoomUrl":"customguitar_body_pickups_humbuckersinglecoilblack_image.png",
                                    "imageUrl":"customguitar_body_pickups_humbuckersinglecoilblack_smallimage.png",
                                    "iconUrl":"customguitar_body_pickups_humbuckersinglecoilblack_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347776"
                                },
                                {
                                    "id":347788,
                                    "name":"Dual White Humbuckers",
                                    "order":3,
                                    "price":13,
                                    "description":"Dual White Humbuckers description text",
                                    "zoomUrl":"customguitar_body_pickups_dualwhitehumbuckers_image.png",
                                    "imageUrl":"customguitar_body_pickups_dualwhitehumbuckers_smallimage.png",
                                    "iconUrl":"customguitar_body_pickups_dualwhitehumbuckers_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347776"
                                },
                                {
                                    "id":347781,
                                    "name":"Dual Black Humbuckers",
                                    "order":4,
                                    "price":14,
                                    "description":"Dual Black Humbuckers description text",
                                    "zoomUrl":"customguitar_body_pickups_dualblackhumbuckers_image.png",
                                    "imageUrl":"customguitar_body_pickups_dualblackhumbuckers_smallimage.png",
                                    "iconUrl":"customguitar_body_pickups_dualblackhumbuckers_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347776"
                                },
                                {
                                    "id":347785,
                                    "name":"Single P90 Cream",
                                    "order":5,
                                    "price":15,
                                    "description":"Single P90 Cream description text",
                                    "zoomUrl":"customguitar_body_pickups_singlep90cream_image.png",
                                    "imageUrl":"customguitar_body_pickups_singlep90cream_smallimage.png",
                                    "iconUrl":"customguitar_body_pickups_singlep90cream_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347776"
                                },
                                {
                                    "id":347789,
                                    "name":"Single P90 Black",
                                    "order":6,
                                    "price":16,
                                    "description":"Single P90 Black description text",
                                    "zoomUrl":"customguitar_body_pickups_singlep90black_image.png",
                                    "imageUrl":"customguitar_body_pickups_singlep90black_smallimage.png",
                                    "iconUrl":"customguitar_body_pickups_singlep90black_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347776"
                                },
                                {
                                    "id":347782,
                                    "name":"Dual Cream P90",
                                    "order":7,
                                    "price":17,
                                    "description":"Dual Cream P90 description text",
                                    "zoomUrl":"customguitar_body_pickups_dualcreamp90_image.png",
                                    "imageUrl":"customguitar_body_pickups_dualcreamp90_smallimage.png",
                                    "iconUrl":"customguitar_body_pickups_dualcreamp90_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347776"
                                },
                                {
                                    "id":347786,
                                    "name":"Dual Black P90",
                                    "order":8,
                                    "price":18,
                                    "description":"Dual Black P90 description text",
                                    "zoomUrl":"customguitar_body_pickups_dualblackp90_image.png",
                                    "imageUrl":"customguitar_body_pickups_dualblackp90_smallimage.png",
                                    "iconUrl":"customguitar_body_pickups_dualblackp90_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347776"
                                },
                                {
                                    "id":347783,
                                    "name":"Dual White Single Coil",
                                    "order":9,
                                    "price":19,
                                    "description":"Dual White Single Coil description text",
                                    "zoomUrl":"customguitar_body_pickups_dualwhitesinglecoil_image.png",
                                    "imageUrl":"customguitar_body_pickups_dualwhitesinglecoil_smallimage.png",
                                    "iconUrl":"customguitar_body_pickups_dualwhitesinglecoil_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347776"
                                },
                                {
                                    "id":347787,
                                    "name":"Dual Black Single Coil",
                                    "order":10,
                                    "price":20,
                                    "description":"Dual Black Single Coil description text",
                                    "zoomUrl":"customguitar_body_pickups_dualblacksinglecoil_image.png",
                                    "imageUrl":"customguitar_body_pickups_dualblacksinglecoil_smallimage.png",
                                    "iconUrl":"customguitar_body_pickups_dualblacksinglecoil_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347776"
                                }
                            ]
                        },
                        {
                            "id":7,
                            "name":"Bridge",
                            "order":7,
                            "options":[
                                {
                                    "id":{
                                        "347742":347790,
                                        "347743":348047
                                    },
                                    "name":"Chrome Bridge",
                                    "order":{
                                        "347742":1,
                                        "347743":2
                                    },
                                    "price":{
                                        "347742":10,
                                        "347743":12
                                    },
                                    "description":{
                                        "347742":"Chrome Bridge description text",
                                        "347743":"Chrome Bridge description text"
                                    },
                                    "depends_on":[
                                        "347742",
                                        "347743"
                                    ],
                                    "zoomUrl":{
                                        "347742":"customguitar_body_bridge_chromebridge_orientation_left_image.png",
                                        "347743":"customguitar_body_bridge_chromebridge_orientation_right_image.png"
                                    },
                                    "imageUrl":{
                                        "347742":"customguitar_body_bridge_chromebridge_orientation_left_smallimage.png",
                                        "347743":"customguitar_body_bridge_chromebridge_orientation_right_smallimage.png"
                                    },
                                    "iconUrl":{
                                        "347742":"customguitar_body_bridge_chromebridge_orientation_left_thumbnail.png",
                                        "347743":"customguitar_body_bridge_chromebridge_orientation_right_thumbnail.png"
                                    },
                                    "is_salable":{
                                        "347742":"1",
                                        "347743":"1"
                                    },
                                    "configurableProductId":"347777"
                                },
                                {
                                    "id":{
                                        "347742":347791,
                                        "347743":348048
                                    },
                                    "name":"Black Bridge",
                                    "order":{
                                        "347742":3,
                                        "347743":4
                                    },
                                    "price":{
                                        "347742":15,
                                        "347743":15
                                    },
                                    "description":{
                                        "347742":"Black Bridge description text",
                                        "347743":"Black Bridge description text"
                                    },
                                    "depends_on":[
                                        "347742",
                                        "347743"
                                    ],
                                    "zoomUrl":{
                                        "347742":"customguitar_body_bridge_blackbridge_orientation_left_image.png",
                                        "347743":"customguitar_body_bridge_blackbridge_orientation_right_image.png"
                                    },
                                    "imageUrl":{
                                        "347742":"customguitar_body_bridge_blackbridge_orientation_left_smallimage.png",
                                        "347743":"customguitar_body_bridge_blackbridge_orientation_right_smallimage.png"
                                    },
                                    "iconUrl":{
                                        "347742":"customguitar_body_bridge_blackbridge_orientation_left_thumbnail.png",
                                        "347743":"customguitar_body_bridge_blackbridge_orientation_right_thumbnail.png"
                                    },
                                    "is_salable":{
                                        "347742":"1",
                                        "347743":"1"
                                    },
                                    "configurableProductId":"347777"
                                },
                                {
                                    "id":{
                                        "347742":347792,
                                        "347743":348049
                                    },
                                    "name":"Gold Bridge",
                                    "order":{
                                        "347742":5,
                                        "347743":6
                                    },
                                    "price":{
                                        "347742":20,
                                        "347743":20
                                    },
                                    "description":{
                                        "347742":"Gold Bridge description text",
                                        "347743":"Gold Bridge description text"
                                    },
                                    "depends_on":[
                                        "347742",
                                        "347743"
                                    ],
                                    "zoomUrl":{
                                        "347742":"customguitar_body_bridge_goldbridge_orientation_left_image.png",
                                        "347743":"customguitar_body_bridge_goldbridge_orientation_right_image.png"
                                    },
                                    "imageUrl":{
                                        "347742":"customguitar_body_bridge_goldbridge_orientation_left_smallimage.png",
                                        "347743":"customguitar_body_bridge_goldbridge_orientation_right_smallimage.png"
                                    },
                                    "iconUrl":{
                                        "347742":"customguitar_body_bridge_goldbridge_orientation_left_thumbnail.png",
                                        "347743":"customguitar_body_bridge_goldbridge_orientation_right_thumbnail.png"
                                    },
                                    "is_salable":{
                                        "347742":"1",
                                        "347743":"1"
                                    },
                                    "configurableProductId":"347777"
                                }
                            ]
                        },
                        {
                            "id":8,
                            "name":"Tailpiece",
                            "order":8,
                            "options":[
                                {
                                    "id":347793,
                                    "name":"Chrome Tailpiece",
                                    "order":1,
                                    "price":11,
                                    "description":"Chrome Tailpiece description text",
                                    "zoomUrl":"customguitar_body_tailpiece_chrometailpiece_image.png",
                                    "imageUrl":"customguitar_body_tailpiece_chrometailpiece_smallimage.png",
                                    "iconUrl":"customguitar_body_tailpiece_chrometailpiece_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347778"
                                },
                                {
                                    "id":347794,
                                    "name":"Black Tailpiece",
                                    "order":2,
                                    "price":15,
                                    "description":"Black Tailpiece description text",
                                    "zoomUrl":"customguitar_body_tailpiece_blacktailpiece_image.png",
                                    "imageUrl":"customguitar_body_tailpiece_blacktailpiece_smallimage.png",
                                    "iconUrl":"customguitar_body_tailpiece_blacktailpiece_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347778"
                                },
                                {
                                    "id":347795,
                                    "name":"Gold Tailpiece",
                                    "order":3,
                                    "price":20,
                                    "description":"Gold Tailpiece description text",
                                    "zoomUrl":"customguitar_body_tailpiece_goldtailpiece_image.png",
                                    "imageUrl":"customguitar_body_tailpiece_goldtailpiece_smallimage.png",
                                    "iconUrl":"customguitar_body_tailpiece_goldtailpiece_thumbnail.png",
                                    "is_salable":"1",
                                    "configurableProductId":"347778"
                                }
                            ]
                        },
                        {
                            "id":33,
                            "name":"Knobs",
                            "order":9,
                            "options":[
                                {
                                    "id":{
                                        "347742":348043,
                                        "347743":347890
                                    },
                                    "name":"Chrome Knob",
                                    "order":{
                                        "347742":1,
                                        "347743":2
                                    },
                                    "price":{
                                        "347742":9,
                                        "347743":9
                                    },
                                    "description":{
                                        "347742":"Chrome Knob description text",
                                        "347743":"Chrome Knob description text"
                                    },
                                    "depends_on":[
                                        "347742",
                                        "347743"
                                    ],
                                    "zoomUrl":{
                                        "347742":"customguitar_body_knobs_chromeknob_orientation_left_image.png",
                                        "347743":"customguitar_body_knobs_chromeknob_orientation_right_image.png"
                                    },
                                    "imageUrl":{
                                        "347742":"customguitar_body_knobs_chromeknob_orientation_left_smallimage.png",
                                        "347743":"customguitar_body_knobs_chromeknob_orientation_right_smallimage.png"
                                    },
                                    "iconUrl":{
                                        "347742":"customguitar_body_knobs_chromeknob_orientation_left_thumbnail.png",
                                        "347743":"customguitar_body_knobs_chromeknob_orientation_right_thumbnail.png"
                                    },
                                    "is_salable":{
                                        "347742":"1",
                                        "347743":"1"
                                    },
                                    "configurableProductId":"347889"
                                },
                                {
                                    "id":{
                                        "347742":347891,
                                        "347743":348044
                                    },
                                    "name":"Black Knob",
                                    "order":{
                                        "347742":3,
                                        "347743":4
                                    },
                                    "price":{
                                        "347742":12,
                                        "347743":12
                                    },
                                    "description":{
                                        "347742":"Black Knob description text",
                                        "347743":"Black Knob description text"
                                    },
                                    "depends_on":[
                                        "347742",
                                        "347743"
                                    ],
                                    "zoomUrl":{
                                        "347742":"customguitar_body_knobs_blackknob_orientation_left_image.png",
                                        "347743":"customguitar_body_knobs_blackknob_orientation_right_image.png"
                                    },
                                    "imageUrl":{
                                        "347742":"customguitar_body_knobs_blackknob_orientation_left_smallimage.png",
                                        "347743":"customguitar_body_knobs_blackknob_orientation_right_smallimage.png"
                                    },
                                    "iconUrl":{
                                        "347742":"customguitar_body_knobs_blackknob_orientation_left_thumbnail.png",
                                        "347743":"customguitar_body_knobs_blackknob_orientation_right_thumbnail.png"
                                    },
                                    "is_salable":{
                                        "347742":"1",
                                        "347743":"1"
                                    },
                                    "configurableProductId":"347889"
                                },
                                {
                                    "id":{
                                        "347742":347892,
                                        "347743":348045
                                    },
                                    "name":"Gold Knob",
                                    "order":{
                                        "347742":5,
                                        "347743":6
                                    },
                                    "price":{
                                        "347742":15,
                                        "347743":15
                                    },
                                    "description":{
                                        "347742":"Gold Knob description text",
                                        "347743":"Gold Knob description text"
                                    },
                                    "depends_on":[
                                        "347742",
                                        "347743"
                                    ],
                                    "zoomUrl":{
                                        "347742":"customguitar_body_knobs_goldknob_orientation_left_image.png",
                                        "347743":"customguitar_body_knobs_goldknob_orientation_right_image.png"
                                    },
                                    "imageUrl":{
                                        "347742":"customguitar_body_knobs_goldknob_orientation_left_smallimage.png",
                                        "347743":"customguitar_body_knobs_goldknob_orientation_right_smallimage.png"
                                    },
                                    "iconUrl":{
                                        "347742":"customguitar_body_knobs_goldknob_orientation_left_thumbnail.png",
                                        "347743":"customguitar_body_knobs_goldknob_orientation_right_thumbnail.png"
                                    },
                                    "is_salable":{
                                        "347742":"1",
                                        "347743":"1"
                                    },
                                    "configurableProductId":"347889"
                                },
                                {
                                    "id":{
                                        "347742":347893,
                                        "347743":348046
                                    },
                                    "name":"Wood Knob",
                                    "order":{
                                        "347742":7,
                                        "347743":8
                                    },
                                    "price":{
                                        "347742":25,
                                        "347743":25
                                    },
                                    "description":{
                                        "347742":"Wood Knob description text",
                                        "347743":"Wood Knob description text"
                                    },
                                    "depends_on":[
                                        "347742",
                                        "347743"
                                    ],
                                    "zoomUrl":{
                                        "347742":"customguitar_body_knobs_woodknob_orientation_left_image.png",
                                        "347743":"customguitar_body_knobs_woodknob_orientation_right_image.png"
                                    },
                                    "imageUrl":{
                                        "347742":"customguitar_body_knobs_woodknob_orientation_left_smallimage.png",
                                        "347743":"customguitar_body_knobs_woodknob_orientation_right_smallimage.png"
                                    },
                                    "iconUrl":{
                                        "347742":"customguitar_body_knobs_woodknob_orientation_left_thumbnail.png",
                                        "347743":"customguitar_body_knobs_woodknob_orientation_right_thumbnail.png"
                                    },
                                    "is_salable":{
                                        "347742":"1",
                                        "347743":"1"
                                    },
                                    "configurableProductId":"347889"
                                }
                            ]
                        }
                    ]
                }
            ]
        };
    </script>

<div id="customizer-container"></div>

<?php /*
Customizer
<pre id="product_data"></pre>
<script type="text/javascript">
    //
    // Test Ajax Request to get product data.
    // Change productId after creating a simple product in admin panel
    //
    jQuery(document).ready(function($){
        $.ajax({
            url: "<?php echo $this->getUrl(); ?>customizer/index/product",
            dataType: 'json',
            type: 'post',
            data: { productId: 1 },
            success: function(data){
                var data = JSON.stringify(data);
                $("#product_data").html(data);
            }
        });
    });
</script>
 */ ?>