<?php

?>
<script type="text/javascript">
// override
productForm._processValidationResult = function(transport) {
	var override;
	
    var response = transport.responseText.evalJSON();
    if (response.error){
        if (response.attribute && $(response.attribute)) {
            $(response.attribute).setHasError(true, productForm);
            Validation.ajaxError($(response.attribute), response.message);
            if (!Prototype.Browser.IE){
                $(response.attribute).focus();
            }
        }
        else if ($('messages')) {
            $('messages').innerHTML = '<ul class="messages"><li class="error-msg"><ul><li>' + response.message + '</li></ul></li></ul>';
        }
    }
    else{
        //productForm._submit();
    }
};
</script>
